### ISSUE TITLE
Cannot get `gd` for SwiftUI working even though code actions are working

### ISSUE THREAD

**Issue by xiifain** [kkharji/xbase#194]
I'm not sure if I'm mis-configuring something because I cannot get go to definition not working. but as you can see in the picture the code suggestions are working correctly in here.

![image](https://user-images.githubusercontent.com/49685742/233845559-5a9fa634-3497-4691-99dd-ad0fe3c68bb8.png)

**Comment by xiifain** [comment]
Here is my config for `xbase`.

![image](https://user-images.githubusercontent.com/49685742/233845913-ce82247d-a556-4840-8a74-bdce7af7350e.png)

**Comment by kkharji** [comment]
Hello @xiifain. Yes, unfortunately  this is a known issue. Planning to support it in 0.5 release. You can subscribe to get updates on #96. 

Meanwhile I'm closing this as duplication.
