### ISSUE TITLE
How to install Xbase through lazy.nvim

### ISSUE THREAD

**Issue by johntheocs** [kkharji/xbase#241]
Hello, thanks for developing this wonderful plugin. I am new in nvim, lazy.nvim, and xbase. Would you mind telling me how to install xbase through lazy.nvim, since lazy.nvim is popular now? Thank you so much.

**Comment by ali-ahsan-ali** [comment]
Wondering if this can be reopened. As a new comer to the VIM world I would like an easier tutorial. There seems to be alot of inferred knowledge about neovim for this setup
